# Generated by Django 3.0.5 on 2020-04-27 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_customuserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='cu_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
