# Generated by Django 3.0.5 on 2020-04-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200427_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='cu_book_id',
            field=models.CharField(default='fe90cad8-805c-4ec3-8917-a39fcc00842b', max_length=255),
            preserve_default=False,
        ),
    ]
