# Generated by Django 3.0.5 on 2020-04-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20200428_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='rating_count',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
