# Generated by Django 3.0.5 on 2020-04-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200428_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='cu_book_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuserprofile',
            name='cu_book_progress_note',
            field=models.CharField(default='', max_length=300),
        ),
    ]
